mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\worldwind-2.3.1.jar -DgroupId=com.ursulagis -DartifactId=worldwind -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\worldwindx-2.3.1.jar -DgroupId=com.ursulagis -DartifactId=worldwindx -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true

mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\gluegen-rt.jar -DgroupId=com.ursulagis -DartifactId=gluegen-rt -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\gluegen-rt-natives-linux-amd64.jar -DgroupId=com.ursulagis -DartifactId=gluegen-rt-natives-linux-amd64 -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\gluegen-rt-natives-linux-i586.jar -DgroupId=com.ursulagis -DartifactId=gluegen-rt-natives-linux-i586 -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\gluegen-rt-natives-macosx-universal.jar -DgroupId=com.ursulagis -DartifactId=gluegen-rt-natives-macosx-universal -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\gluegen-rt-natives-windows-amd64.jar -DgroupId=com.ursulagis -DartifactId=gluegen-rt-natives-windows-amd64 -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\gluegen-rt-natives-windows-i586.jar -DgroupId=com.ursulagis -DartifactId=gluegen-rt-natives-windows-i586 -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\jogl-all.jar -DgroupId=com.ursulagis -DartifactId=jogl-all -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\jogl-all-natives-linux-amd64.jar -DgroupId=com.ursulagis -DartifactId=jogl-all-natives-linux-amd64 -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\jogl-all-natives-linux-i586.jar -DgroupId=com.ursulagis -DartifactId=jogl-all-natives-linux-i586 -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\jogl-all-natives-macosx-universal.jar -DgroupId=com.ursulagis -DartifactId=jogl-all-natives-macosx-universal -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\jogl-all-natives-windows-amd64.jar -DgroupId=com.ursulagis -DartifactId=jogl-all-natives-windows-amd64 -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=D:\worskpaces\workspaceHackaton2015\WorldWindJava_CE\WorldWindJava\jogl-all-natives-windows-i586.jar -DgroupId=com.ursulagis -DartifactId=jogl-all-natives-windows-i586 -Dversion=2.3.1 -Dpackaging=jar -DgeneratePom=true